baseURL = "https://mayuxiang.com"
languageCode = "zh-CN"
title = "马宇翔@河南大学"
enableRobotsTXT = true

disableKinds = ["taxonomy", "term", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[outputs]
  home = ["HTML"]
